// AUTO-GENERATED by scripts/generate-gallery-data.mjs
// Do not edit manually. Run: npm run optimize:gallery

export interface GalleryItemSrc {
  full: string;
  avif: string;
  thumb: string;
}

export interface GalleryItemVideo {
  desktop: string;
  mobile: string;
  poster: string;
}

export interface GalleryItem {
  id: string;
  type: "image" | "video";
  category: "kitchen" | "wardrobe";
  title: string;
  width?: number;
  height?: number;
  blurData?: string;
  src: GalleryItemSrc;
  video?: GalleryItemVideo;
}

export const galleryItems: GalleryItem[] = [
  {
    "id": "1",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 419,
    "blurData": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAsABUB8JbACdADD0eAMUYgA98QuI9jr3hGHH5vblUfVwoWOd9+I2issz+QJqo6TEcVcFfRinaR3B/VpKAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-001.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-001.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-001.webp"
    }
  },
  {
    "id": "2",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 410,
    "blurData": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoQAAsABUB8JagCdABhIs4AAPzUj4GgNqte+L2WBBoMf3ifRDBV4DHSTM3CjwIHdAwtVhH1KBUEqxcMhP+i8AAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-002.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-002.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-002.webp"
    }
  },
  {
    "id": "3",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 400,
    "height": 600,
    "blurData": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBACdASoQABgAPzmEuVOvKKWisAgB4CcJYgC7ABM9984h9nWdF6+sAADMeGhdJYcHXvyHYl49N2UIo+jlWFa61qFhk4TKaCN5kXVDKcYSaQ4J6+xwUWvhAzcadOEMglRITwAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-003.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-003.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-003.webp"
    }
  },
  {
    "id": "4",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 400,
    "blurData": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAsABUB8JQBOgCKRZ9EMzAD419+4zWyHhsLcGgK1YbrWTIsMEYZkXisroAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-004.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-004.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-004.webp"
    }
  },
  {
    "id": "5a",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 337,
    "blurData": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoQAAkABUB8JQBOgBLbqTAA+R7CfJ6Vnafy9h0ume6fHYTBTuL9Y5rex14OMbJ344eBgAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-new2.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-new2.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-new2.webp"
    }
  },
  {
    "id": "5",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 438,
    "height": 600,
    "blurData": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQAwCdASoQABYAPzmEuVOvKKWisAgB4CcJYgCdABhZ8tN2pQYAAPtq7epX1eui9TaANd1rV4tZ8+xP2in5mupAJKsKoXbgtqXE4gIle7ARJMcx4zPcMC2tJEgOvizsBhwAAA==",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-005.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-005.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-005.webp"
    }
  },
  {
    "id": "6",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 400,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAsABUB8JQBOgCIj2avZIAAA/gMU7tYiDRA+l6ryXcooGWRDrV74s+nJHoK49TBcNA8Zw2PE2AAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-new.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-new.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-new.webp"
    }
  },
  {
    "id": "7",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 400,
    "blurData": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAsABUB8JbACdAC1w4L47MAA/o8V2a278qKJgdZ+sI6JDxYKR7qxhO3nHipCM28fFNcLbuqNBTdQ34AAAA==",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-007.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-007.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-007.webp"
    }
  },
  {
    "id": "13",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 400,
    "blurData": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAsABUB8JbACdAEVE6v3boAA/o1F5+SyY4J0geaMsDtYarcx+qXPngp4TLh3WQ5p2p5mTwvXC1H1NdocAAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-real-013.webp",
      "avif": "/media/optimized/images/avif/kitchen-real-013.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-real-013.webp"
    }
  },
  {
    "id": "16",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAkABUB8JYgCdAEJozfVAAD+4I6t/ibf+5I/5skXwv9MGF9KK6wmAAA=",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-001.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-001.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-001.webp"
    }
  },
  {
    "id": "17",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoQAAkABUB8JQBOgA6dAQAA/sRi2+A3nHMCn6D0xlMn3J5snt+mfPGKuUXqvNlOX1UAAA==",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-002.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-002.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-002.webp"
    }
  },
  {
    "id": "18",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkABUB8JQBOgBslDjAAAPRvXVVTWQdSpNTY001cs5gxXGD6cK/D2TPF4XvIHp5q3gAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-003.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-003.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-003.webp"
    }
  },
  {
    "id": "19",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 313,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAgABUB8JQBOgBbwWK5hsAAA+FJN4qh+NGIF0KIBum1I3DLYTp3nMrqc0XNO8jtwmONpEFrMeAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-004.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-004.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-004.webp"
    }
  },
  {
    "id": "20",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 372,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAQCdASoQAAoABUB8JYwC7ABSgAD+lxJC2YOv1rQ6SZjchCvRnmBdLo8zzxMvp5cIaUQPzZGdnZZYSPfNYAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-005.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-005.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-005.webp"
    }
  },
  {
    "id": "21",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkABUB8JYgCdACYaQQgAP5g5JXyiDbl/wMKd0OcLyyaHkLZvUga9X9eW4WkyBtOcAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-006.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-006.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-006.webp"
    }
  },
  {
    "id": "22",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAkABUB8JQBOgB4QRubamAAA4ipsqx9w2NUaSzyR6zIPqmGy4X2591pU7q/epMEBymgP5agAAA==",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-007.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-007.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-007.webp"
    }
  },
  {
    "id": "23",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkABUB8JQBOgBxooR+WAAD+ahFfsd/5xRu+hVXvw9YO4YhiYI5KmTyRo0Oas/s0mG3gxyWUAAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-008.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-008.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-008.webp"
    }
  },
  {
    "id": "24",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABwAQCdASoQAAkABUB8JQAAUJkyQAD+gsomRNx1Y9Gh1RI6DbRJ3mMg88/LADXpnUV+l2/mnnlZIWW+mYS67Hz11d+TYSAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-009.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-009.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-009.webp"
    }
  },
  {
    "id": "25",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoQAAkABUB8JZACdABrhl1AAMlKofiwRs0MHzhoJVOSbN/uudECyo1H5nvh63UxDJh7+nLf+wAAAA==",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-010.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-010.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-010.webp"
    }
  },
  {
    "id": "26",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 255,
    "blurData": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoQAAcABUB8JYwAAoXoV0AA/js/Ws05OVlyi93t2eBW/lj8/kzEw8kFyQHB0noDVF/QqfJMOAA=",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-011.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-011.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-011.webp"
    }
  },
  {
    "id": "27",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 255,
    "blurData": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoQAAcABUB8JZACsADRz+7THAAA/r+N6/FkGrAoXXWSuFiWLun57g15F64FmRus/sOyQAAA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-012.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-012.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-012.webp"
    }
  },
  {
    "id": "28",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 255,
    "blurData": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAcABUB8JQBOgB+ExJPOAAD9m89elFcUiqOhMetbCfqT2mmPGclsnlOHXxLlLTgrsYTWDENgyuAmSwAAAA==",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-013.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-013.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-013.webp"
    }
  },
  {
    "id": "29",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 255,
    "blurData": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAAcABUB8JYgCdAEDSdVYCAAA/mwmHjNBV2HqvdGcLVNFk73wNNTBsuu+z9p6HXUHxZq2gAA=",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-014.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-014.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-014.webp"
    }
  },
  {
    "id": "30",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 450,
    "blurData": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwABUB8JYgCdAC7HrVjcbQAAP4ZRG9sUPrykKNZXXL+rk91G4HW4eGm7qVt45sjvCM539FQpsymdre0K11I0zwQpIvjwe0AdWknYiyjP5OtwqJAAA==",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-015.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-015.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-015.webp"
    }
  },
  {
    "id": "31",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 450,
    "blurData": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAwABUB8JQBOgBxv1+ySPMIAAP5kUFQtfn3GJaRMM/OxbYYbByyrJZ8kn7w45UtPPC/BYuPD6lIpGE+aN66rtTd7plT1WDydYCwA",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-016.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-016.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-016.webp"
    }
  },
  {
    "id": "32",
    "type": "image",
    "category": "kitchen",
    "title": "",
    "width": 600,
    "height": 324,
    "blurData": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkABUB8JQBdgCBzlcZRjAD9reZDPlO5WMwTHP5VoIJMw+VfRc8IopGuljfRwyCvFoOzzQYACq7E1nrYlbsAAAA=",
    "src": {
      "full": "/media/optimized/images/full/kitchen-render-017.webp",
      "avif": "/media/optimized/images/avif/kitchen-render-017.avif",
      "thumb": "/media/optimized/images/thumb/kitchen-render-017.webp"
    }
  },
  {
    "id": "33",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 338,
    "blurData": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAkABUB8JQBOgBhdr4YAAOHowu96NMFOEbiVLY/Ea0tWhHFQGqIvl8+rx0Wb4SbFiUkqAAA=",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-real-001.webp",
      "avif": "/media/optimized/images/avif/wardrobe-real-001.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-real-001.webp"
    }
  },
  {
    "id": "34",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 338,
    "blurData": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoQAAkABUB8JYwCdIIjGQ0NqxCAAP7TjXny15msDtiRsAM6dlSa5SjlyvF2peo6KcAAAA==",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-real-002.webp",
      "avif": "/media/optimized/images/avif/wardrobe-real-002.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-real-002.webp"
    }
  },
  {
    "id": "35",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 400,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAsABUB8JagCdAED/HEhuKQAAPKEE+KnUGqRZBZ5U+j0VJnp6R0ad6jaWg4JjHzhc5QGb4Hi8AAA",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-real-003.webp",
      "avif": "/media/optimized/images/avif/wardrobe-real-003.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-real-003.webp"
    }
  },
  {
    "id": "36",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 400,
    "blurData": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAsABUB8JaAC7AC1NsEIAP6wG92x+P35sTMSf+XMKDujwQVe5duh9Jftl+g8/HPWuOKUUs/r8zxa9cAAAA==",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-real-004.webp",
      "avif": "/media/optimized/images/avif/wardrobe-real-004.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-real-004.webp"
    }
  },
  {
    "id": "37",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 400,
    "blurData": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAsABUB8JbACdABwNM0AAP7k5NnaNXIMdixLXEKsvtWzkh0wzZzJjAtsNlTo7qr6ONxEGvLBpsIulKpHslmL908gAA==",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-real-005.webp",
      "avif": "/media/optimized/images/avif/wardrobe-real-005.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-real-005.webp"
    }
  },
  {
    "id": "38",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAkABUB8JYgCdACwmtghAADhTQTjs5UwslCdxuBT5vC9+bGiBPFwmp/x1gAA",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-render-001.webp",
      "avif": "/media/optimized/images/avif/wardrobe-render-001.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-render-001.webp"
    }
  },
  {
    "id": "39",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkABUB8JQBOgBo2muT0EAD+gxxj72Ie2Fhp6USuRa+XuLZ4nQTV9nvSxpGYvGd4Z8dnvaXKZAAA",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-render-002.webp",
      "avif": "/media/optimized/images/avif/wardrobe-render-002.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-render-002.webp"
    }
  },
  {
    "id": "40",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkABUB8JYgCdADdF98WAADiFuHAHnUJjGgSK0Aij81kqdRjB0xd34+wJn3kfEoxCEiM+kbyD4tB6+cAAA==",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-render-003.webp",
      "avif": "/media/optimized/images/avif/wardrobe-render-003.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-render-003.webp"
    }
  },
  {
    "id": "41",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkABUB8JQBOgBePoOTNgAD+xvVHJJseYfTxuA8YoKLpu+5Qn0uzJ+bajBupqybRwTgzfWNeWAAA",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-render-004.webp",
      "avif": "/media/optimized/images/avif/wardrobe-render-004.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-render-004.webp"
    }
  },
  {
    "id": "42",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 335,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkABUB8JYgCdAEVI2EaFgAA/l9N9+ROI8zCMBy4XYv6iLlHpob8rgEw6s1EDkKgd6M1o5qK7gAA",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-render-005.webp",
      "avif": "/media/optimized/images/avif/wardrobe-render-005.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-render-005.webp"
    }
  },
  {
    "id": "43",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 255,
    "blurData": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAAcABUB8JZACdAEXQhneqkAA/lUnXOKqo1XCKpZBdhL2LePPg4Ev/LJvLjYYS/52TsMAAAA=",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-render-006.webp",
      "avif": "/media/optimized/images/avif/wardrobe-render-006.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-render-006.webp"
    }
  },
  {
    "id": "44",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 255,
    "blurData": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAcABUB8JYgCdADG8FuTKYAA+PAW+yaCtjzGyM/bUTVWLX5pN2rm/xwwQGFNKu/Mp8+i0UAwSkVFAAA=",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-render-007.webp",
      "avif": "/media/optimized/images/avif/wardrobe-render-007.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-render-007.webp"
    }
  },
  {
    "id": "45",
    "type": "image",
    "category": "wardrobe",
    "title": "",
    "width": 600,
    "height": 255,
    "blurData": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAcABUB8JZgCdAEXdaleeVjAAP5pXokCfJLd/IYjxjng0ZpF9K1hV1UTaP+stj6cpIdDQvBD8AAA",
    "src": {
      "full": "/media/optimized/images/full/wardrobe-render-008.webp",
      "avif": "/media/optimized/images/avif/wardrobe-render-008.avif",
      "thumb": "/media/optimized/images/thumb/wardrobe-render-008.webp"
    }
  }
];
